parameters:

    pagosonlinegateway.gateway: "https://gateway.pagosonline.net/apps/gateway/index.html"
    pagosnlinegateway.controller.route.name: "pagosonlinegateway_execute"
    pagosnlinegateway.form.type.wrapper.class: "Scastells\\PagosonlineGatewayBundle\\Services\\Wrapper\\PagosonlineGatewayTypeWrapper"
    pagosnlinegateway.routes.loader.class: "Scastells\\PagosonlineGatewayBundle\\Router\\PagosonlineGatewayRoutesLoader"